AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sam Template for test services

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  ServicesApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
  GetUserInfoFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: cmd/lambdas/getUserInfo
      Handler: getUserInfo
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /api/v1/users
            Method: GET
            RestApiId: !Ref ServicesApi
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          USERS_TABLE: users
      Policies:
        - AmazonDynamoDBFullAccess
  GetTweetsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: cmd/lambdas/getTweets
      Handler: getTweets
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /api/v1/tweets
            Method: GET
            RestApiId: !Ref ServicesApi
      Policies:
        - Statement:
            - Sid: SSMGetParameterPolicy
              Effect: Allow
              Action:
                - ssm:GetParameters
                - ssm:GetParameter
              Resource: '*'
  GetVisitsCounterFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: cmd/lambdas/getVisitsCounter
      Handler: getTweets
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /api/v1/metrics
            Method: GET
            RestApiId: !Ref ServicesApi
      Policies:
        - AmazonDynamoDBFullAccess
        - Statement:
            - Sid: SSMGetParameterPolicy
              Effect: Allow
              Action:
                - ssm:GetParameters
                - ssm:GetParameter
              Resource: '*'
  UpdateUserInfoFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: cmd/lambdas/updateUserInfo
      Handler: updateUser
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /api/v1/users
            Method: PUT
            RestApiId: !Ref ServicesApi
      Policies:
        - AmazonDynamoDBFullAccess
  UsersTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: test-services-users
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      ProvisionedThroughput:
        ReadCapacityUnits: 0
        WriteCapacityUnits: 0
  AtomicCounters:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: test-services-atomic-counter
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      ProvisionedThroughput:
        ReadCapacityUnits: 0
        WriteCapacityUnits: 0

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  UsersEndpoint:
    Description: "API Gateway endpoint URL  Dev environment for Users API"
    Value: !Sub "https://${ServicesApi}.execute-api.${AWS::Region}.amazonaws.com/dev/api/v1/users"
  TweetsEndpoint:
    Description: "API Gateway endpoint URL Dev environment for Tweets API"
    Value: !Sub "https://${ServicesApi}.execute-api.${AWS::Region}.amazonaws.com/dev/api/v1/tweets"
  MetricsEndpoint:
    Description: "API Gateway endpoint URL Dev environment for Metrics API"
    Value: !Sub "https://${ServicesApi}.execute-api.${AWS::Region}.amazonaws.com/dev/api/v1/metrics"
  GetUserInfoFunction:
    Description: "GetUserInfoFunction ARN"
    Value: !GetAtt GetUserInfoFunction.Arn
